<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title>WP Eatery - Contact Us</title>';
echo '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">';
echo '<link href="http://fonts.googleapis.com/css?family=Fugaz+One|Muli|Open+Sans:400,700,800" rel="stylesheet" type="text/css" />';
echo '<link href="css/style.css" rel="stylesheet" type="text/css">';
echo '</head>';
echo '<body>';
echo '<div id="wrapper">';
include 'header.php';
include 'menu.php';
echo '<div id="content" class="clearfix">';
echo '<aside>';
echo '<h2>Mailing Address</h2>';
echo '<h3>1385 Woodroffe Ave<br>';
echo 'Ottawa, ON K4C1A4</h3>';
echo '<h2>Phone Number</h2>';
echo '<h3>(613)727-4723</h3>';
echo '<h2>Fax Number</h2>';
echo '<h3>(613)555-1212</h3>';
echo '<h2>Email Address</h2>';
echo '<h3>info@wpeatery.com</h3>';
echo '</aside>';
echo '<div class="main">';
echo '<h1>Sign up for our newsletter</h1>';
echo '<p>Please fill out the following form to be kept up to date with news, specials, and promotions from the WP eatery!</p>';
echo '<form name="frmNewsletter" id="frmNewsletter" method="post" action="db_config.php">';
echo '<table>';
echo '<tr>';
echo '<td>First Name:</td>';
echo '<td><input type="text" name="firstName" size="40"></td>';
echo '</tr>';
echo '<tr>';
echo '<td>Last Name:</td>';
echo '<td><input type="text" name="lastName"  size="40"></td>';
echo '</tr>';
echo '<tr>';
echo '<td>Phone Number:</td>';
echo '<td><input type="text" name="phoneNumber"  size="40"></td>';
echo '</tr>';
echo '<tr>';
echo '<td>Email Address:</td>';
echo '<td><input type="text" name="emailAddress"  size="40">';
echo '</tr>';
echo '<tr>';
echo '<td>Username:</td>';
echo '<td><input type="text" name="username" size="20">';
echo '</tr>';
echo '<tr>';
echo '<td>How did you hear<br> about us?</td>';
echo '<td>';
echo '<select name="referrer" size="1">';
echo '<option>Select referer</option>';
echo '<option value="newspaper">Newspaper</option>';
echo '<option value="radio">Radio</option>';
echo '<option value="tv">Television</option>';
echo '<option value="other">Other</option>';
echo '</select>';
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td colspan="2"><input type="submit" name="submit" value="Sign up!">&nbsp;&nbsp;<input type="reset" name="btnReset" id="btnReset" value="Reset Form"></td>';
echo '</tr>';
echo '</table>';
echo '</form>';
echo '</div><!-- End Main -->';
echo '</div><!-- End Content -->';
include 'footer.php';
echo '</div><!-- End Wrapper -->';
echo '</body>';
echo '';
echo '';
?>