<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title>WP Eatery - Home</title>';
echo '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">';
echo '<link href="css/style.css" rel="stylesheet" type="text/css">';
echo '</head>';
echo '<body>';
echo '<div id="wrapper">';
include 'header.php';
include 'menu.php';
include 'class_lib.php';
$eventItem1 = new Eventitem("St. Pattys Day Party","Tuesday Oct 17, 2017","7pm","$35.00");
$eventItem2 = new Eventitem ("Samys Spring Fling!","Saturday Oct 18, 2017","8pm","$40.00");
echo '<div id="content" class="clearfix">';
echo '<aside>';
echo"'<h2>".date("l")."'s Specials</h2>";
echo '<hr>';
echo '<img src="images/burger_small.jpg" alt="Burger" title="Mondays Special - Burger">';
echo '<h3>The WP Burger</h3>';
echo '<p>Freshly made all-beef patty served up with homefries - $14</p>';
echo '<hr>';
echo '<img src="images/kebobs.jpg" alt="Kebobs" title="WP Kebobs">';
echo '<h3>WP Kebobs</h3>';
echo '<p>Tender cuts of beef and chicken, served with your choice of side - $17</p>';
echo '<hr>';
echo '<h2>Private Dining</h2>';
echo '<img src="images/dining_room_sm.jpg" width="228" alt="Dining Room" title="The WP Eatery Dining Room">';
echo '<p>Call us to find out more about our private dinning options.</p>';
echo '</aside>';
echo '<div class="main">';
echo '<h1>Welcome to WP Eatery!</h1>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>';
echo '<h3>Upcoming Events ...</h3>';
echo '<p>';
echo '<strong class="event">St. Pattys Day Party</strong><br/>';
echo '<strong>Date:</strong> Tuesday Oct 17, 2017<br/>';
echo '<strong>Time:</strong> 7pm<br/>';
echo '<strong>Price:</strong> $35.00<br/>';
echo 'Join us for an authentic Irish four course meal, complete with shepards pie and one green beer!';
echo '</p>';
echo '<p>';
echo '<strong class="event">Samys Spring Fling!</strong><br/>';
echo '<strong>Date:</strong> Saturday Oct 18, 2017<br/>';
echo '<strong>Time:</strong> 8pm<br/>';
echo '<strong>Price:</strong> $40.00<br/>';
echo 'Join us for to kick off the beginning of spring! This event will include 4 of Samys infamous appetizers and one cocktail!';
echo '</p>';
echo '<h2>Book your Private Party!</h2>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>';
echo '</div><!-- End Main -->';
echo '</div><!-- End Content -->';
include 'footer.php';
echo '</div><!-- End Wrapper -->';
echo '</body>';
echo '</html>';
echo '';
?>